# Use the official Nginx image as the base image
FROM nginx:alpine

# Copy Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Copy static website files
COPY path/to/static/website /usr/share/nginx/html

# Expose port 80 (default HTTP port)
EXPOSE 80

# Command to start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]

server {
    listen 80;
    server_name  https://08c7-213-137-72-0.ngrok-free.app;
}
