# Use the official Nginx image as the base image
FROM nginx:alpine

# Copy Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Copy static website files
COPY . /usr/share/nginx/html

# Expose port 80 (default HTTP port)
EXPOSE 81

# Command to start Nginx when the container starts
CMD ["nginx", "-g", "daemon off;"]

