version: '3'
services:
  app:
    build:
      context: .
      dockerfile: app/dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
  web:
    build:
      context: .
      dockerfile: web/dockerfile
    ports:
      - "80:80"
    volumes:
      - ./:/usr/share/nginx/html
