version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    ports:
      - "5000:5000"
    volumes:
      - .:/app

  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "8080:80"  # Changed host port to 8080 to avoid conflict
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html

networks:
  default:
    driver: bridge
