# Dockerfile for Nginx Static Website

# Use the official Nginx image as the base image
FROM nginx:latest

# Copy Nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Copy static website files to Nginx default public directory
COPY . /usr/share/nginx/html

# Expose the port that Nginx runs on
EXPOSE 80

# Command to start Nginx
CMD ["nginx", "-g", "daemon off;"]
