version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: nginx_web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/usr/share/nginx/html/index.html
    ports:
      - "8082:80"

  python_app:
    build: .
    container_name: python_app
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
