apiVersion: v1
kind: ConfigMap
metadata:
  name: project-int-nginx-config
  namespace: demo-app
data:
  default.conf: |
    server {
        listen 80;
        location /healthz {
            return 200 'OK';
            add_header Content-Type text/plain;
        }

        location /readiness {
            return 200 'OK';
            add_header Content-Type text/plain;
        }
    }
